[general]
import = [
"~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[font]
size = 15
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }

[window]
  decorations = "none"
  dynamic_padding = false
  dynamic_title   = true
  opacity         = 1.0
#  startup_mode    = "Maximized"

[window.padding]
x = 7
y = 0
